apiVersion: v1
kind: Pod
metadata:
  name: selenium
spec:
  containers:
    - image: hub.docker.com/r/selenium/hub
      name: selenium
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP